[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

# Указываем, какие модули относятся к вашему проекту (first party)
known_first_party = ["project", "avatars"]

# Указать сторонние библиотеки (third party)
known_third_party = ["PIL", "boto3", "django", "storages"]